### ISSUE TITLE
希望更正本人的博客名称，加入链接地址，并修改简介

### ISSUE THREAD

**Issue by lengge86** [qianguyihao/blog-list#11]
首先感谢作者的收录和辛勤工作。

本人博客的名称不对，不是“冷金乘”，应改为“心的道理”。

似乎应像其他博客一样，在名称下插入链接。链接为：https://stephenleng.com

现有的简介有点长，放在这里不太合适，我浓缩了一下：
“作者是浙江大学历史学院博士生，现为美国弗吉尼亚大学访问学者，学术兴趣为思想史、情绪史、历史哲学、人文主义哲学和心理学。博客创作的内容包含随笔、文化批评、心理学、国际问题和技术，希望能分别从科学和艺术两个角度兴起读者对生活的感悟，并着重批判当代文化中的一些谬误、偏见、狂妄、愚蠢和欺骗。”

非常感谢。

**Comment by qianguyihao** [comment]
好，已更新。

1. 博客链接是我遗漏了，已补充。

2. 收录的标题我都是统一用博主们的笔名（网名），而不是博客名；既然你想用博客名，那就尊重你的选择。

感谢你对本项目的关注。你的博客让我很受益。
