### ISSUE TITLE
搜录的这些博客过于同质化

### ISSUE THREAD

**Issue by ziliudi** [qianguyihao/blog-list#12]
我看了一下，基本上都是搞IT的，没什么看头

**Comment by qianguyihao** [comment]
1. 越是搞IT的人，越愿意在网络上输出。
2. 搭建独立博客需要会一点技术门槛，这就把绝大多数非IT的人拦截在外了。
3. 如果你有质量好的非IT博客，欢迎推荐。

**Comment by qianguyihao** [comment]
> 是的，而且还有一个博客 https://leonhe.cn 居然是要注册才能看的，还说什么个人博客不希望在网上到处都能看到 完全违背了博客的分享这一基本原则

这不妨碍 leonhe.cn 的博文内容质量就是很高。设置一些阅读门槛，是博主作者本人的意愿。我的筛选标准，是内容优先。
