### ISSUE TITLE
博客补充

### ISSUE THREAD

**Issue by AabyssZG** [qianguyihao/blog-list#15]
博客名称：AabyssZG
博客地址：https://blog.zgsec.cn/
博客介绍：渊龙Sec安全团队的负责人，专注于网络安全领域，主要涉及云安全、红蓝攻防和渗透测试等方面，博客主要记录我在网络安全方面的技术学习、成长经历和自己的心理历程。弱小和无知不是生存的障碍，傲慢才是！

**Comment by qianguyihao** [comment]
你好，暂时未达收录条件，抱歉。您的博客文章，目前才写了一年，大多是流水账记录为主，缺少成体系的长文和深度思考。请继续加油，假以时日肯定能收录进来。
