### ISSUE TITLE
章工的核电站恢复了

### ISSUE THREAD

**Issue by xcbyao** [qianguyihao/blog-list#8]
新网址：
https://hwv430.blogspot.com/

信息来源：
https://twitter.com/suexiy/status/1600335320439889921?s=20&t=2waKExzU_FxIWblNt-BGwA

**Comment by qianguyihao** [comment]
哇塞，感谢。已更新 readme

**Comment by xcbyao** [comment]
无奈更新😂，估计是章工上次喝茶的缘故，我刚点进来，网址又换了，建议都放上去吧，目前似乎是两个网址来回倒腾了

https://hwv430.blogspot.com/
https://wc41.blogspot.com/
